# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-09 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('posted_on_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_date', models.DateTimeField()),
                ('annual_salary', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('url', models.URLField()),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
